### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by Perni1984** [bolonio/a11y-github-actions#2]
Hi @bolonio,

we are interested in using your code or parts of your code in our own github actions, but unfortunately I couldn't find any licensing information in the github repository. Could you kindly let me know which license you intend to have for you publicly shared code?

Thanks!

Christoph

**Comment by bolonio** [comment]
Hi @Perni1984, 

I've just added the **MIT License** to the repository. Now you can use my code in your projects.

PS: If you have any suggestion for how this project could be improved, please read the [contributing guidelines](https://github.com/bolonio/a11y-github-actions/blob/main/CONTRIBUTING.md).

Adrián
